sudo: false
language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - "pip install -e ."
    - "pip install 'coverage>=3.7,<3.8' coveralls"
script:
    - "PYTHONFAULTHANDLER=x timeout -sABRT 30s nosetests -vsd"
after_success:
    - coveralls
